#!/bin/env python3

from qlearningagent.QAgent import QAgent, loadAgentFromFile
import argparse
import train_self
import train_stockfish
import train_pgn
import os.path

parser = argparse.ArgumentParser(description='')

parser.add_argument('-f', '--file', type=str, default='chess.sav')
parser.add_argument('-a', '--agent', type=str, default='self')
parser.add_argument('-e', type=float, help='Epsilon', default=-1)
parser.add_argument('-d', type=float, help='Discount', default=-1)
parser.add_argument('-l', type=float,help='LearningRate', default=-1)
parser.add_argument('-i', default=50, type=int, help='Iterations')
parser.add_argument('-t', '--threads', default=1, type=int, help='Amount of games played at the same time')
parser.add_argument('-win', action='store_true', help='For those beings that think Windows is a good OS')

def getAgent(agent):
    if agent == 'self':
        return train_self.runEpisode
    elif agent == 'stockfish':
        return train_stockfish.runEpisode
    elif agent == 'pgn':
        return train_pgn.runEpisode

if __name__ == "__main__":
    args = parser.parse_args()
    if os.path.isfile('chess.sav'):
        qAgent = loadAgentFromFile('chess.sav')
    else:
        qAgent = QAgent('chess.sav', 0.5, 0.7, 0.6)

    if args.win:
        train_stockfish.STOCKFISH_BIN = './stockfish-win/stockfish.exe'

    if args.e >= 0:
        qAgent.setEpsilon(args.e)
    if args.d >= 0:
        qAgent.setDiscount(args.d)
    if args.l >= 0:
        qAgent.setLearningRate(args.l)

    runEpisode = getAgent(args.agent)

    for _ in range(args.i):
        runEpisode(qAgent)

